# Lesson 3 - Gates Provided by Pyquil

-----

This goal of this lesson is to introduce the user to the pre-defined gates that come from the pyquil.gates file.  We go through each gate with a short explination, as well as at least one working example for each.  

After going through all of the gates, we will cover how Pyquil allows us to define and use our own gates.

Before proceeding, please consider reading the previous lessons in this series, which covers all of the pyquil basics of programs and measurements in Pyquil:

Lesson 1 - Intro to Programs and Measurements
Lesson 2 - Creating More Complex Programs

https://github.com/dkoch92/Quantum-Algorithm-Tutorials

---

If you wish to skip around this lesson for the examples of code, please run the following cell of code below to ensure all functions are imported properly:

In [306]:
import numpy as np
from pyquil.quil import Program
from pyquil.gates import I, H, X, Y, Z, S, T, PHASE, RX, RY, RZ, CNOT, CZ, CPHASE, CPHASE10, CPHASE01, CPHASE00, SWAP, ISWAP, CSWAP, CCNOT
from pyquil.api import QVMConnection

def SD(qubit_index,total_qubits):
    standard = abs( qubit_index - (total_qubits-1) )
    return standard

qvm = QVMConnection()

-------
# Single Qubit Gates
-------

All of the following gates act on a single qubit.

## I

The single qubit Identity Gate

$$
\begin{bmatrix} 
1 & 0\\ 
0 & 1
\end{bmatrix}
$$

The effect of this gate renders the qubit's state unchanged.

In [256]:
from pyquil.gates import I

p_I = Program()
print('Initial State: ',qvm.wavefunction(p_I))
p_I.inst(I(0))
print('Identity: ',qvm.wavefunction(p_I))

Initial State:  (1+0j)|0>
Identity:  (1+0j)|0>


## Hadamard (H)

The single qubit Identity Gate

$$
\begin{bmatrix} 
1 & 1\\ 
1 & -1
\end{bmatrix}
$$

The effect of this gate is as follows:

$$\textbf{H} |0\rangle = \frac{1}{\sqrt{2}}(|0\rangle + |1\rangle)$$

$$\textbf{H} |1\rangle = \frac{1}{\sqrt{2}}(|0\rangle - |1\rangle)$$

This gate results in a qubit being in a 50 / 50 superposition of states |$0\rangle$ and |$1\rangle$.

In [182]:
from pyquil.gates import H, X

p_H = Program(H(0))
print('H on |0>: ',qvm.wavefunction(p_H))
p_H = Program(X(0),H(0))
print('H on |1>: ',qvm.wavefunction(p_H))

H on |0>:  (0.7071067812+0j)|0> + (0.7071067812+0j)|1>
H on |1>:  (0.7071067812+0j)|0> + (-0.7071067812+0j)|1>


# Pauli Operators
------

## X

$$
\begin{bmatrix} 
0 & 1\\ 
1 & 0
\end{bmatrix}
$$

The effect of this gate flip's a qubits |0$\rangle$ and |1$\rangle$ amplitudes

In [174]:
from pyquil.gates import X
p_X = Program()
print('Initial qubit 0: ',qvm.wavefunction(p_X))
p_X.inst(X(0))
print('X on qubit 0: ',qvm.wavefunction(p_X))
p_X.inst(H(0))
print('H on qubit 0: ',qvm.wavefunction(p_X))
p_X.inst(X(0))
print('X on qubit 0: ',qvm.wavefunction(p_X))
p_X.inst(H(0))
print('H on qubit 0: ',qvm.wavefunction(p_X))

Initial qubit 0:  (1+0j)|0>
X on qubit 0:  (1+0j)|1>
H on qubit 0:  (0.7071067812+0j)|0> + (-0.7071067812+0j)|1>
X on qubit 0:  (-0.7071067812+0j)|0> + (0.7071067812+0j)|1>
H on qubit 0:  (-1+0j)|1>


## Y

$$
\begin{bmatrix} 
0 & -i\\ 
i & 0
\end{bmatrix}
$$

The effect of this gate flip's a qubits |0$\rangle$ and |1$\rangle$ amplitudes and multiplys by imaginary numbers (phase)

In [173]:
from pyquil.gates import Y
p_Y = Program()
print('Initial qubit 0: ',qvm.wavefunction(p_Y))
p_Y.inst(Y(0))
print('Y on qubit 0: ',qvm.wavefunction(p_Y))
p_Y.inst(H(0))
print('H on qubit 0: ',qvm.wavefunction(p_Y))
p_Y.inst(Y(0))
print('Y on qubit 0: ',qvm.wavefunction(p_Y))
p_Y.inst(H(0))
print('H on qubit 0: ',qvm.wavefunction(p_Y))

Initial qubit 0:  (1+0j)|0>
Y on qubit 0:  1j|1>
H on qubit 0:  0.7071067812j|0> + -0.7071067812j|1>
Y on qubit 0:  (-0.7071067812+0j)|0> + (-0.7071067812+0j)|1>
H on qubit 0:  (-1+0j)|0>


## Z

$$
\begin{bmatrix} 
1 & 0\\ 
0 & -1
\end{bmatrix}
$$

The effect of this gate leaves a qubit's |0$\rangle$ amplitude unchanged, while multiplying by -1 (phase) to a qubit's |1$\rangle$ amplitude.

In [177]:
from pyquil.gates import Z
p_Z = Program()
print('Initial qubit 0: ',qvm.wavefunction(p_Z))
p_Z.inst(Z(0))
print('Z on qubit 0: ',qvm.wavefunction(p_Z))
p_Z.inst(H(0))
print('H on qubit 0: ',qvm.wavefunction(p_Z))
p_Z.inst(Z(0))
print('Z on qubit 0: ',qvm.wavefunction(p_Z))
p_Z.inst(H(0))
print('H on qubit 0: ',qvm.wavefunction(p_Z))

Initial qubit 0:  (1+0j)|0>
Z on qubit 0:  (1+0j)|0>
H on qubit 0:  (0.7071067812+0j)|0> + (0.7071067812+0j)|1>
Z on qubit 0:  (0.7071067812+0j)|0> + (-0.7071067812+0j)|1>
H on qubit 0:  (1+0j)|1>


# Phase Gates
------

## PHASE  (R$_{\phi}$)

$$
\begin{bmatrix} 
1 & 0\\ 
0 & e^{i\phi}
\end{bmatrix}
$$

A gate similar to the Z gate.  It leaves a qubit's |0$\rangle$ amplitude unchanged, while multiplying by a phase $e^{i\phi}$ to a qubit's |1$\rangle$ amplitude.

In [191]:
import math as m
from pyquil.gates import PHASE
phi = m.pi
print('phi = pi -- this is equivilant to a Z gate')
print('  ')
p_Rp = Program(H(0))
print('Initial Mixed State: ',qvm.wavefunction(p_Rp))
p_Rp.inst(PHASE(phi,0))
print('S Gate: ',qvm.wavefunction(p_Rp))
p_Rp.inst(PHASE(phi,0))
print('S Gate: ',qvm.wavefunction(p_Rp))

phi = pi -- this is equivilant to a Z gate
  
Initial Mixed State:  (0.7071067812+0j)|0> + (0.7071067812+0j)|1>
S Gate:  (0.7071067812+0j)|0> + (-0.7071067812+0j)|1>
S Gate:  (0.7071067812+0j)|0> + (0.7071067812+0j)|1>


## S

A pre-defined gate for R$_{\phi}$, $\phi$=$\frac{\pi}{2}$

$$
\begin{bmatrix} 
1 & 0\\ 
0 & i
\end{bmatrix}
$$

A gate similar to the Z gate.  It leaves a qubit's |0$\rangle$ amplitude unchanged, while multiplying by i (phase) to a qubit's |1$\rangle$ amplitude.

In [187]:
from pyquil.gates import S
p_S = Program(H(0))
print('Initial Mixed State: ',qvm.wavefunction(p_S))
p_S.inst(S(0))
print('S Gate: ',qvm.wavefunction(p_S))
p_S.inst(S(0))
print('S Gate: ',qvm.wavefunction(p_S))

Initial Mixed State:  (0.7071067812+0j)|0> + (0.7071067812+0j)|1>
S Gate:  (0.7071067812+0j)|0> + 0.7071067812j|1>
S Gate:  (0.7071067812+0j)|0> + (-0.7071067812+0j)|1>


## T

A pre-defined gate for R$_{\phi}$, $\phi$=$\frac{\pi}{4}$

$$
\begin{bmatrix} 
1 & 0\\ 
0 & e^{i\frac{\pi}{4}}
\end{bmatrix}
$$

A gate similar to the Z gate.  It leaves a qubit's |0$\rangle$ amplitude unchanged, while multiplying by $e^{i\frac{\pi}{4}}$ (phase) to a qubit's |1$\rangle$ amplitude.

In [188]:
from pyquil.gates import T
p_T = Program(X(0))
print('Initial State: ',qvm.wavefunction(p_T))
p_T.inst(T(0))
print('T Gate: ',qvm.wavefunction(p_T))
p_T.inst(T(0))
print('T Gate: ',qvm.wavefunction(p_T))

Initial State:  (1+0j)|1>
S Gate:  (0.7071067812+0.7071067812j)|1>
S Gate:  1j|1>


# Rotation Gates
-------

The follow gates all represent rotations of a state on a Bloch spehere.  A Bloch sphere is a visual representation that maps the state of a qubit to a location on the surface of a sphere, radius = 1.  An image of a Bloch sphere and it's axes is given below:
![title](Bloch_Sphere.png)

## R$_x$($\theta$)

A rotation gate, representing a rotation around the x-axis on a Bloch Sphere

$$
\begin{bmatrix} 
cos(\frac{\theta}{2}) & -i \cdot sin(\frac{\theta}{2})\\ 
-i \cdot sin(\frac{\theta}{2}) & cos(\frac{\theta}{2})
\end{bmatrix}
$$


In [219]:
from pyquil.gates import RX
theta = m.pi/2
p_Rx = Program()
print('Initial State: ',qvm.wavefunction(p_Rx),'   = |0>')
print('theta = pi/2 -- rotations by 90 degrees around the x-axis (counter-clockwise)')
print('  ')
p_Rx.inst(RX(theta,0))
print('Rx(90) Gate: ',qvm.wavefunction(p_Rx),'   = -Y')
p_Rx.inst(RX(theta,0))
print('Rx(90) Gate: ',qvm.wavefunction(p_Rx),'   = |1>')
p_Rx.inst(RX(theta,0))
print('Rx(90) Gate: ',qvm.wavefunction(p_Rx),'   = Y')
p_Rx.inst(RX(theta,0))
print('Rx(90) Gate: ',qvm.wavefunction(p_Rx),'   = |0>')

Initial State:  (1+0j)|0>    = |0>
theta = pi/2 -- rotations by 90 degrees around the x-axis (counter-clockwise)
  
Rx(90) Gate:  (0.7071067812+0j)|0> + -0.7071067812j|1>    = -Y
Rx(90) Gate:  -1j|1>    = |1>
Rx(90) Gate:  (-0.7071067812+0j)|0> + -0.7071067812j|1>    = Y
Rx(90) Gate:  (-1+0j)|0>    = |0>


## R$_y$($\theta$)

A rotation gate, representing a rotation around the y-axis on a Bloch Sphere

$$
\begin{bmatrix} 
cos(\frac{\theta}{2}) & -sin(\frac{\theta}{2})\\ 
sin(\frac{\theta}{2}) & cos(\frac{\theta}{2})
\end{bmatrix}
$$


In [220]:
from pyquil.gates import RY
theta = m.pi/2
p_Ry = Program()
print('Initial State: ',qvm.wavefunction(p_Ry),'   = |0>')
print('theta = pi/2 -- rotations by 90 degrees around the y-axis (counter-clockwise)')
print('  ')
p_Ry.inst(RY(theta,0))
print('Ry(90) Gate: ',qvm.wavefunction(p_Ry),'   = X')
p_Ry.inst(RY(theta,0))
print('Ry(90) Gate: ',qvm.wavefunction(p_Ry),'   = |1>')
p_Ry.inst(RY(theta,0))
print('Ry(90) Gate: ',qvm.wavefunction(p_Ry),'   = -X')
p_Ry.inst(RY(theta,0))
print('Ry(90) Gate: ',qvm.wavefunction(p_Ry),'   = |0>')


Initial State:  (1+0j)|0>    = |0>
theta = pi/2 -- rotations by 90 degrees around the y-axis (counter-clockwise)
  
Ry(90) Gate:  (0.7071067812+0j)|0> + (0.7071067812+0j)|1>    = X
Ry(90) Gate:  (1+0j)|1>    = |1>
Ry(90) Gate:  (-0.7071067812+0j)|0> + (0.7071067812+0j)|1>    = -X
Ry(90) Gate:  (-1+0j)|0>    = |0>


## R$_z$($\theta$)

A rotation gate, representing a rotation around the z-axis on a Bloch Sphere

$$
\begin{bmatrix} 
e^{\frac{-i\theta}{2}} & 0\\ 
0 & e^{\frac{i\theta}{2}}
\end{bmatrix}
$$


In [228]:
from pyquil.gates import RZ
theta = m.pi/2
p_Rz = Program(H(0))
print('Initial State: ',qvm.wavefunction(p_Rz),' = X')
print('theta = pi -- rotations by 90 degrees around the z-axis (counter-clockwise)')
print('  ')
p_Rz.inst(RZ(theta,0))
print('Rz(90) Gate: ',qvm.wavefunction(p_Rz),'   = Y')
p_Rz.inst(RZ(theta,0))
print('Rz(90) Gate: ',qvm.wavefunction(p_Rz),'   = -X')
p_Rz.inst(RZ(theta,0))
print('Rz(90) Gate: ',qvm.wavefunction(p_Rz),'   = -Y')
p_Rz.inst(RZ(theta,0))
print('Rz(90) Gate: ',qvm.wavefunction(p_Rz),'   = X')

Initial State:  (0.7071067812+0j)|0> + (0.7071067812+0j)|1>  = X
theta = pi -- rotations by 90 degrees around the z-axis (counter-clockwise)
  
Rz(90) Gate:  (0.5-0.5j)|0> + (0.5+0.5j)|1>    = Y
Rz(90) Gate:  -0.7071067812j|0> + 0.7071067812j|1>    = -X
Rz(90) Gate:  (-0.5-0.5j)|0> + (-0.5+0.5j)|1>    = -Y
Rz(90) Gate:  (-0.7071067812+0j)|0> + (-0.7071067812+0j)|1>    = X


# Two Qubit Control Gates
---------

All of the following gates act on 2 qubits.

## CNOT

This gate uses a 'target qubit' and a 'control qubit'.  The effect of this gate is as follows:

$$\textbf{CNOT} \hspace{.2cm} |00\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |00\rangle $$
$$\textbf{CNOT} \hspace{.2cm} |01\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |01\rangle $$
$$\textbf{CNOT} \hspace{.2cm} |10\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |11\rangle $$
$$\textbf{CNOT} \hspace{.2cm} |11\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |10\rangle $$

In this notation, the first qubit is the control and the second qubit is the target.  If the first qubit is in the state |$0\rangle$, nothing happens to the second qubit.  If the first qubit is in the state |$1\rangle$, then the amplitudes of the second qubit are flipped.

Another way to think of this gate is as a 'control-X' gate, where the state of the control qubit determines whether or not an X gate is applied to the target qubit.

$$
\begin{bmatrix} 
1 & 0 & 0 & 0\\ 
0 & 1 & 0 & 0\\ 
0 & 0 & 0 & 1\\ 
0 & 0 & 1 & 0\\ 
\end{bmatrix}
$$


In [240]:
from pyquil.gates import CNOT
control_qubit = SD(0,2)
target_qubit  = SD(1,2)

p_CNOT = Program(I(control_qubit),I(target_qubit))
print('Initial State: ',qvm.wavefunction(p_CNOT))
p_CNOT.inst(CNOT(control_qubit,target_qubit))
print('After CNOT: ',qvm.wavefunction(p_CNOT))
print('  ')

p_CNOT = Program(X(control_qubit),I(target_qubit))
print('Initial State: ',qvm.wavefunction(p_CNOT))
p_CNOT.inst(CNOT(control_qubit,target_qubit))
print('After CNOT: ',qvm.wavefunction(p_CNOT))
print('  ')

p_CNOT = Program(I(control_qubit),X(target_qubit))
print('Initial State: ',qvm.wavefunction(p_CNOT))
p_CNOT.inst(CNOT(control_qubit,target_qubit))
print('After CNOT: ',qvm.wavefunction(p_CNOT))
print('  ')

p_CNOT = Program(X(control_qubit),X(target_qubit))
print('Initial State: ',qvm.wavefunction(p_CNOT))
p_CNOT.inst(CNOT(control_qubit,target_qubit))
print('After CNOT: ',qvm.wavefunction(p_CNOT))
print('  ')

Initial State:  (1+0j)|00>
After CNOT:  (1+0j)|00>
  
Initial State:  (1+0j)|10>
After CNOT:  (1+0j)|11>
  
Initial State:  (1+0j)|01>
After CNOT:  (1+0j)|01>
  
Initial State:  (1+0j)|11>
After CNOT:  (1+0j)|10>
  


The code above confirms the effect of the CNOT gate.  But this effect also applies to mixed states (which is where it's power comes from in more complex algorithms):

In [241]:
from pyquil.gates import CNOT
control_qubit = SD(0,2)
target_qubit  = SD(1,2)

p_CNOT = Program(X(control_qubit),H(control_qubit),I(target_qubit))
print('Initial State: ',qvm.wavefunction(p_CNOT))
p_CNOT.inst(CNOT(control_qubit,target_qubit))
print('After CNOT: ',qvm.wavefunction(p_CNOT))
print('  ')

Initial State:  (0.7071067812+0j)|00> + (-0.7071067812+0j)|10>
After CNOT:  (0.7071067812+0j)|00> + (-0.7071067812+0j)|11>
  


## CZ (Control-Z)

The control-Z gate works similarly to the CNOT gate, only instead of flipping the target qubit (applying an X gate), we apply a Z gate.

$$\textbf{CZ} \hspace{.2cm} |00\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |00\rangle $$
$$\textbf{CZ} \hspace{.2cm} |01\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |01\rangle $$
$$\textbf{CZ} \hspace{.2cm} |10\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |10\rangle $$
$$\textbf{CZ} \hspace{.2cm} |11\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} -|11\rangle $$

Recall that a Z gates leaves a qubit in the state |$0\rangle$ untouched, while flipping the sign on a qubit in the state |$1\rangle$.  Thus, the CZ gate only affects the state |$11\rangle$, as shown above.

$$
\begin{bmatrix} 
1 & 0 & 0 & 0\\ 
0 & 1 & 0 & 0\\ 
0 & 0 & 1 & 0\\ 
0 & 0 & 0 & -1\\ 
\end{bmatrix}
$$

In [242]:
from pyquil.gates import CZ
control_qubit = SD(0,2)
target_qubit  = SD(1,2)

p_CZ = Program(H(control_qubit),H(target_qubit))
print('Initial State: ',qvm.wavefunction(p_CZ))
p_CZ.inst(CZ(control_qubit,target_qubit))
print('After CZ: ',qvm.wavefunction(p_CZ))


Initial State:  (0.5+0j)|00> + (0.5+0j)|01> + (0.5+0j)|10> + (0.5+0j)|11>
After CZ:  (0.5+0j)|00> + (0.5+0j)|01> + (0.5+0j)|10> + (-0.5+0j)|11>


## Control Phase Gates

The following four gates will be bundled together, since they all represent the same general effect

#### CPHASE($\phi$) |$11\rangle$

$$
\begin{bmatrix} 
1 & 0 & 0 & 0\\ 
0 & 1 & 0 & 0\\ 
0 & 0 & 1 & 0\\ 
0 & 0 & 0 & e^{i\phi}\\ 
\end{bmatrix}
$$

#### CPHASE($\phi$) |$10\rangle$

$$
\begin{bmatrix} 
1 & 0 & 0 & 0\\ 
0 & 1 & 0 & 0\\ 
0 & 0 & e^{i\phi} & 0\\ 
0 & 0 & 0 & 1\\ 
\end{bmatrix}
$$

#### CPHASE($\phi$) |$01\rangle$

$$
\begin{bmatrix} 
1 & 0 & 0 & 0\\ 
0 & e^{i\phi} & 0 & 0\\ 
0 & 0 & 1 & 0\\ 
0 & 0 & 0 & 1\\ 
\end{bmatrix}
$$

#### CPHASE($\phi$) |$00\rangle$

$$
\begin{bmatrix} 
e^{i\phi} & 0 & 0 & 0\\ 
0 & 1 & 0 & 0\\ 
0 & 0 & 1 & 0\\ 
0 & 0 & 0 & 1\\ 
\end{bmatrix}
$$


By standard convention the CPHASE gate is the one that acts on the state |$11\rangle$, but all of the gates are the same in principle.  Each of the variations of the CPHASE gate picks out one of the four states and applies a phase operation.

In [287]:
from pyquil.gates import CPHASE,CPHASE10,CPHASE01,CPHASE00
phi = m.pi
control_qubit = SD(0,2)
target_qubit  = SD(1,2)

p_CP11 = Program(H(control_qubit),H(target_qubit))
p_CP10 = Program(H(control_qubit),H(target_qubit))
p_CP01 = Program(H(control_qubit),H(target_qubit))
p_CP00 = Program(H(control_qubit),H(target_qubit))
print('phi = pi    --   same effect as a Z gate  ')
print('_____Initial State:_____')
print(qvm.wavefunction(p_CP11))
print(' ')

p_CP11.inst(CPHASE(phi,control_qubit,target_qubit))
print('CPHASE: ',qvm.wavefunction(p_CP11))
p_CP10.inst(CPHASE10(phi,control_qubit,target_qubit))
print('CPHASE10: ',qvm.wavefunction(p_CP10))
p_CP01.inst(CPHASE01(phi,control_qubit,target_qubit))
print('CPHASE01: ',qvm.wavefunction(p_CP01))
p_CP00.inst(CPHASE00(phi,control_qubit,target_qubit))
print('CPHASE00: ',qvm.wavefunction(p_CP00))


phi = pi    --   same effect as a Z gate  
_____Initial State:_____
(0.5+0j)|00> + (0.5+0j)|01> + (0.5+0j)|10> + (0.5+0j)|11>
 
CPHASE:  (0.5+0j)|00> + (0.5+0j)|01> + (0.5+0j)|10> + (-0.5+0j)|11>
CPHASE10:  (0.5+0j)|00> + (0.5+0j)|01> + (-0.5+0j)|10> + (0.5+0j)|11>
CPHASE01:  (0.5+0j)|00> + (-0.5+0j)|01> + (0.5+0j)|10> + (0.5+0j)|11>
CPHASE00:  (-0.5+0j)|00> + (0.5+0j)|01> + (0.5+0j)|10> + (0.5+0j)|11>


# Swapping Gates
------

The following four gates all perform a "swap", whereby the states of two qubits are

## SWAP

The SWAP gate causes two qubits to trade states.

$$\textbf{SWAP} \hspace{.2cm} |00\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |00\rangle $$
$$\textbf{SWAP} \hspace{.2cm} |01\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |11\rangle $$
$$\textbf{SWAP} \hspace{.2cm} |10\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |01\rangle $$
$$\textbf{SWAP} \hspace{.2cm} |11\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |11\rangle $$

A simple way of viewing the effect of this gate is it switches the numbers on each state.  As a result, we can see that the SWAP gate has no effect on the states |$00\rangle$ and |$11\rangle$.

$$
\begin{bmatrix} 
1 & 0 & 0 & 0\\ 
0 & 0 & 1 & 0\\ 
0 & 1 & 0 & 0\\ 
0 & 0 & 0 & 1\\ 
\end{bmatrix}
$$

In [288]:
from pyquil.gates import SWAP
qubit0 = SD(0,2)
qubit1 = SD(1,2)

p_SWAP = Program(H(0),H(1),CPHASE10(m.pi,qubit0,qubit1))
print('Initial State: ',qvm.wavefunction(p_SWAP))
print(' ')

p_SWAP.inst(SWAP(qubit0,qubit1))
print('  SWAP: ',qvm.wavefunction(p_SWAP))


Initial State:  (0.5+0j)|00> + (0.5+0j)|01> + (-0.5+0j)|10> + (0.5+0j)|11>
 
  SWAP:  (0.5+0j)|00> + (-0.5+0j)|01> + (0.5+0j)|10> + (0.5+0j)|11>


## ISWAP

This gate produces a similar effect as the SWAP gate, but applies a a phase operation of $\textit{i}$ to the swapped states.

$$
\begin{bmatrix} 
1 & 0 & 0 & 0\\ 
0 & 0 & i & 0\\ 
0 & i & 0 & 0\\ 
0 & 0 & 0 & 1\\ 
\end{bmatrix}
$$

In [271]:
from pyquil.gates import ISWAP
qubit0 = SD(0,2)
qubit1 = SD(1,2)

p_ISWAP = Program(H(0),H(1),CPHASE10(m.pi,qubit0,qubit1))
print('Initial State: ',qvm.wavefunction(p_ISWAP))
print(' ')

p_ISWAP.inst(ISWAP(qubit0,qubit1))
print('  ISWAP: ',qvm.wavefunction(p_ISWAP))

Initial State:  (0.5+0j)|00> + (0.5+0j)|01> + (-0.5+0j)|10> + (0.5+0j)|11>
 
  ISWAP:  (0.5+0j)|00> + (-0-0.5j)|01> + 0.5j|10> + (0.5+0j)|11>


## ISWAP($\phi$)

A more general version of the ISWAP gate, whereby one can specify any phase operation to be applied to the swapped states.

$$
\begin{bmatrix} 
1 & 0 & 0 & 0\\ 
0 & 0 & e^{i\phi} & 0\\ 
0 & e^{i\phi} & 0 & 0\\ 
0 & 0 & 0 & 1\\ 
\end{bmatrix}
$$

In [272]:
from pyquil.gates import PSWAP
qubit0 = SD(0,2)
qubit1 = SD(1,2)
phi = m.pi
print('phi = pi   --   same effect as a -1 phase operation')

p_PSWAP = Program(H(0),H(1),CPHASE10(m.pi,qubit0,qubit1))
print('Initial State: ',qvm.wavefunction(p_PSWAP))
print(' ')

p_PSWAP.inst(PSWAP(phi,qubit0,qubit1))
print('  PSWAP(pi): ',qvm.wavefunction(p_PSWAP))

phi = pi   --   same effect as a -1 phase operation
Initial State:  (0.5+0j)|00> + (0.5+0j)|01> + (-0.5+0j)|10> + (0.5+0j)|11>
 
  PSWAP(pi):  (0.5+0j)|00> + (0.5+0j)|01> + (-0.5+0j)|10> + (0.5+0j)|11>


# 3 Qubit Control Gates
----

The following two gates take 3 qubites as inputs.  They are essentially higher order versions of the CNOT and SWAP gates, adding one extra control qubit to each.

## CSWAP

The control-swap gate uses a control qubit tp determine whether or not to apply a SWAP gate to two target qubits.  If the control qubit is in the state |$1\rangle$, then a SWAP gate is performed.  Examples:

$$\textbf{CSWAP} \hspace{.2cm} |010\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |010\rangle $$
$$\textbf{CSWAP} \hspace{.2cm} |101\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |110\rangle $$
$$\textbf{CSWAP} \hspace{.2cm} |110\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |101\rangle $$
$$\textbf{CSWAP} \hspace{.2cm} |111\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |111\rangle $$

This gate is also sometimes refered to as a Fredkin Gate.

$$
\begin{bmatrix} 
1 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\ 
0 & 1 & 0 & 0 & 0 & 0 & 0 & 0\\ 
0 & 0 & 1 & 0 & 0 & 0 & 0 & 0\\ 
0 & 0 & 0 & 1 & 0 & 0 & 0 & 0\\ 
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0\\ 
0 & 0 & 0 & 0 & 0 & 0 & 1 & 0\\ 
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0\\ 
0 & 0 & 0 & 0 & 0 & 0 & 0 & 1\\ 
\end{bmatrix}
$$


In [279]:
from pyquil.gates import CSWAP
control_qubit = SD(0,3)
qubit1 = SD(1,3)
qubit2 = SD(2,3)

p_CSWAP = Program(H(0),H(1),H(2),Z(0),H(0))
print('Initial State: ',qvm.wavefunction(p_CSWAP))
print(' ')

p_CSWAP.inst(CSWAP(control_qubit,qubit1,qubit2))
print('  CSWAP: ',qvm.wavefunction(p_CSWAP))

Initial State:  (0.5+0j)|001> + (0.5+0j)|011> + (0.5+0j)|101> + (0.5+0j)|111>
 
  CSWAP:  (0.5+0j)|001> + (0.5+0j)|011> + (0.5+0j)|110> + (0.5+0j)|111>


## CCNOT

The control-control not gate uses two control qubits to determine if an X gate is applied to a single target qubit.  In principle, one can have as many control gates, not just up to two. Examples:

$$\textbf{CCNOT} \hspace{.2cm} |010\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |010\rangle $$
$$\textbf{CCNOT} \hspace{.2cm} |101\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |101\rangle $$
$$\textbf{CCNOT} \hspace{.2cm} |110\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |111\rangle $$
$$\textbf{CCNOT} \hspace{.2cm} |111\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |110\rangle $$

This gate is also sometimes refered to as a Toffoli Gate.

$$
\begin{bmatrix} 
1 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\ 
0 & 1 & 0 & 0 & 0 & 0 & 0 & 0\\ 
0 & 0 & 1 & 0 & 0 & 0 & 0 & 0\\ 
0 & 0 & 0 & 1 & 0 & 0 & 0 & 0\\ 
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0\\ 
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0\\ 
0 & 0 & 0 & 0 & 0 & 0 & 0 & 1\\ 
0 & 0 & 0 & 0 & 0 & 0 & 1 & 0\\ 
\end{bmatrix}
$$

In [282]:
from pyquil.gates import CCNOT
control_qubit0 = SD(0,3)
control_qubit1 = SD(1,3)
qubit2 = SD(2,3)

p_CCNOT = Program(H(0),H(1),H(2),CPHASE10(m.pi,control_qubit1,qubit2),CPHASE10(m.pi,control_qubit0,control_qubit1))
print('Initial State: ',qvm.wavefunction(p_CCNOT))
print(' ')

p_CCNOT.inst(CCNOT(control_qubit0,control_qubit1,qubit2))
print('  CCNOT: ',qvm.wavefunction(p_CCNOT))

Initial State:  (0.3535533906+0j)|000> + (0.3535533906+0j)|001> + (-0.3535533906+0j)|010> + (0.3535533906+0j)|011> + (-0.3535533906+0j)|100> + (-0.3535533906+0j)|101> + (-0.3535533906+0j)|110> + (0.3535533906+0j)|111>
 
  CCNOT:  (0.3535533906+0j)|000> + (0.3535533906+0j)|001> + (-0.3535533906+0j)|010> + (0.3535533906+0j)|011> + (-0.3535533906+0j)|100> + (-0.3535533906+0j)|101> + (0.3535533906+0j)|110> + (-0.3535533906+0j)|111>


This concludes all of the quantum gates provided by the pquil.gates file. 

## Defining Gates
---

Pyquil allows the user to create more gates beyond the basic set provided above, so long as one can specifiy the gate's matrix representation.  In order for a define gate to be valid, it must be a unitary matrix of size $2^{n} \times 2^{n}$, where n is the number of qubits the gate operators on. Unitary matrices are defines as follows:

$$ UU^{\dagger} = I $$

where I is the identity matrix, and $\dagger$ is the complex conjugate of a matrix.

As a simple example, let's try defining I$^2$, the 2-qubit identity matrix:

In [304]:
import numpy as np

i2 = np.array([[1, 0, 0, 0],
               [0, 1, 0, 0],
               [0, 0, 1, 0],
               [0, 0, 0, 1]])

q0 = SD(0,2)
q1 = SD(1,2)

two_qubits = Program( I(q0),H(q1) ).defgate("I2",i2)
print('_____two_qubit program w/ our defined gate_____')
print(two_qubits)

print('_____before_____')
print(qvm.wavefunction(two_qubits))
print(' ')

two_qubits.inst(("I2",q0,q1))
print('_____after_____')
print(qvm.wavefunction(two_qubits))
print(' ')

_____two_qubit program w/ our defined gate_____
DEFGATE I2:
    1, 0, 0, 0
    0, 1, 0, 0
    0, 0, 1, 0
    0, 0, 0, 1

I 1
H 0

_____before_____
(0.7071067812+0j)|00> + (0.7071067812+0j)|01>
 
_____after_____
(0.7071067812+0j)|00> + (0.7071067812+0j)|01>
 


The I$^2$ operator works as intended, leaveing both states unchanged.  Let's try one more example, defining a gate that applies an X operation to the first qubit, and a Z operation to the second.

To construct this new gate, we can do a tensor product of the two single qubit gates:

$$ X_0 \otimes Z_1 $$

$$
\begin{bmatrix} 
0 & 1 & \\ 
1 & 0 & \\
\end{bmatrix} \hspace{.2cm} \otimes \hspace{.2cm}
\begin{bmatrix} 
1 & 0 & \\ 
0 & -1 & \\
\end{bmatrix}
$$

$$
\begin{bmatrix} 
0 \cdot \begin{bmatrix} 
1 & 0 & \\ 
0 & -1 & \\
\end{bmatrix} & 1 \cdot \begin{bmatrix} 
1 & 0 & \\ 
0 & -1 & \\
\end{bmatrix} & \\ 
1 \cdot \begin{bmatrix} 
1 & 0 & \\ 
0 & -1 & \\
\end{bmatrix} & 0 \cdot \begin{bmatrix} 
1 & 0 & \\ 
0 & -1 & \\
\end{bmatrix} & \\
\end{bmatrix}
$$

$$
\begin{bmatrix} 
0 & 0 & 1 & 0 \\ 
0 & 0 & 0 & -1 \\ 
1 & 0 & 0 & 0 \\ 
0 & -1 & 0 & 0 \\ 
\end{bmatrix}
$$

(what in the heck just happened?...) For a review on tensor products:

https://en.wikipedia.org/wiki/Tensor_product

Let's compare the effect of this matrix with that of applying the X and Z gates seperately:

In [320]:
import numpy as np

xz = np.array([[0, 0,  1,  0],
               [0, 0,  0, -1],
               [1, 0,  0,  0],
               [0, -1, 0,  0]])

q0 = SD(0,2)
q1 = SD(1,2)

two_qubits = Program( H(q0),H(q1),CPHASE10(m.pi,q0,q1) ).defgate("XZ",xz)

print('_____before_____')
print(qvm.wavefunction(two_qubits))
print(' ')

two_qubits.inst(("XZ",q0,q1))
print('_____after XZ Gate_____')
print(qvm.wavefunction(two_qubits))
print(' ')

two_qubits2 = Program(H(q0),H(q1),CPHASE10(m.pi,q0,q1)).inst(X(q0)).inst(Z(q1))
print('_____X and Z Gates Sequentially_____')
print(qvm.wavefunction(two_qubits2))

_____before_____
(0.5+0j)|00> + (0.5+0j)|01> + (-0.5+0j)|10> + (0.5+0j)|11>
 
_____after XZ Gate_____
(-0.5+0j)|00> + (-0.5+0j)|01> + (0.5+0j)|10> + (-0.5+0j)|11>
 
_____X and Z Gates Sequentially_____
(-0.5+0j)|00> + (-0.5+0j)|01> + (0.5+0j)|10> + (-0.5+0j)|11>


Both states are the same, which means our XZ gate did it's job correctly. Using a tensor product to combine any two individually unitary gates into a single higher order gate will always be unitary as well (I will spare you the proof).

Now suppose that we want to define a gate, but not neccessarily for just one program.  For example, both of the examples above defined our custom gates as follows:

---

program = Program(...).DefGate("NAME",matrix)

---

In general, we will always have to manually add custom gates to programs that aren't included in pyquil.gates, unless we go into pyquil.gates ourselves and define them there (do \textbf{NOT} do this!).  But that doesn't mean we can create gate objects elsewhere in our code, or even other codes, and call on them whenever we want.

Pyquil allows us to define gate objects, and then import them into any programs we choose.  To do this, we need the class DefGate, from pyquil.quilbase.  The reason we were able to use DefGate before without explicity importing it, is because it was already imported when we imported Program from pyquil.quil (importing imports... my head is spinning).

Now we want to import DefGate directly and use it to define gates so that we can use them in any program we want:

In [349]:
from pyquil.quilbase import DefGate

xz = np.array([[0, 0,  1,  0],
               [0, 0,  0, -1],
               [1, 0,  0,  0],
               [0, -1, 0,  0]])

xz_gate = DefGate('XZ', xz)
print(xz_gate)

DEFGATE XZ:
    0, 0, 1, 0
    0, 0, 0, -1
    1, 0, 0, 0
    0, -1, 0, 0



As we can see, we have successfully created the gate 'XZ', independent of any program.  Next, we of course want to try it out!

In [351]:
xz = np.array([[0, 0,  1,  0],
               [0, 0,  0, -1],
               [1, 0,  0,  0],
               [0, -1, 0,  0]])
q0 = SD(0,2)
q1 = SD(1,2)

xz_gate = DefGate('XZ', xz)
print('___our custom xz_gate___')
print(xz_gate)

program = Program(H(q0),H(q1),CPHASE10(m.pi,q0,q1))
program.inst( xz_gate, ("XZ",q0,q1) )
print('____.inst( xz_gate, ("XZ",q0,q1) )____')
print(' ')
print(qvm.wavefunction(program))

___our custom xz_gate___
DEFGATE XZ:
    0, 0, 1, 0
    0, 0, 0, -1
    1, 0, 0, 0
    0, -1, 0, 0

____.inst( xz_gate, ("XZ",q0,q1) )____
 
(-0.5+0j)|00> + (-0.5+0j)|01> + (0.5+0j)|10> + (-0.5+0j)|11>


Another successful use of a custom gate (*thunderous applause*).  Since we can create custom gates as their own objects, we can do with them as we please.  In principle, you could create entire libraries of gates and import them as you see fit, so long as you remember to ammend them into your programs.  If you try and use a defined gate in a program without first ammending it, say you forgot to .inst( my_gate ), you will get an error because the program has no idea what you're asking of it.

Lastly, as we have already seen, some gates have parameters that change the their effect on the qubits they operate on.  Pyquil also allows us to create custom gates with parameters.  To do this, we must import 'Paramters' from pyquil.parameters in order to define our own custom callable parameter.

The Parameter function allows us to create a Parameter object class, as shown in the example below.  Once defined, we can use it in creating our gate, and Pyquil will recognize it as an argument.

Let's create the following single qubit custom gate as our example:

$$
\begin{bmatrix} 
cos(\theta) & -sin(\theta) & \\ 
-sin(\theta) & -cos(\theta) & \\
\end{bmatrix}
$$

In [394]:
from pyquil.parameters import Parameter
from pyquil.quilbase import DefGate
import numpy as np

theta = Parameter('theta')
print('The parameter we just defined:  ',theta,'   object type:',type(theta))
print('  ')

rotate = np.array([[quil_cos(theta), -quil_sin(theta)],
                [-quil_sin(theta),-quil_cos(theta)]])

rot_gate = DefGate('Rot', rotate, [theta])
print('____ our rotate gate ___')
print(rot_gate)
print('  ')

rot_p = Program(rot_gate,I(0))
print('____ Initial ____')
print(qvm.wavefunction(rot_p))
print('  ')

rot_p.inst(Rot(np.pi/4)(0))
print('____ After Rot(pi/4) ____')
print(qvm.wavefunction(rot_p))
print('  ')

The parameter we just defined:   %theta    object type: <class 'pyquil.parameters.Parameter'>
  
____ our rotate gate ___
DEFGATE Rot(%theta):
    cos(%theta), -1*sin(%theta)
    -1*sin(%theta), -1*cos(%theta)

  
____ Initial ____
(1+0j)|0>
  
____ After Rot(pi/4) ____
(0.7071067812+0j)|0> + (-0.7071067812+0j)|1>
  


Our custom gate with the parameter 'theta' works! (*and the crowd goes wild*) 

If we look at the gate itself that was printed to console, we see that Pyquil has stored our custom parameter as %theta.  This was the result of ' theta = Parameter('theta') ' before we defined our gate.  However, not all functions will recognize 'theta' as a parameter - only pre-built Pyquil functions like quil_sin and quil_cos.  For example, if we instead wanted to use numpy's np.sin and np.cos, the code would have given us an error telling us that it didn't recognize 'theta'.  

So long story short, if we want to create gates with paramaters, it's best to use Pyquil's pre-built functions when defining our matrices.  If our unitary operation doesn't require a parameter, then all we need is to input it's matrix into DefGate and we're all set!

---

This concludes all of the topics for lesson 3!  I hope you enjoyed this lesson, and I encourage you to take a look at my other .ipynb tutorials!

link: https://github.com/dkoch92/Quantum-Algorithm-Tutorials